### ISSUE TITLE
Automatic partial fill of "Claim Form for Expenses" PDF

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#139]
From a fast search on the internet look like be possible to automatic partial fill the PDF provided by Edinburgh. The fields that we can fill are

- name
- e-mail address
- postal address
- date
- pupose
- host

We don't want to store bank account details! And I don't think that the time required to automatic flll the expenses fields worth.

**Comment by shoaibsufi** [comment]
might be a guide or GID at a face to face led by Giacomo

**Comment by shoaibsufi** [comment]
or demo online system based on Edinburgh finance claims for their staff

**Comment by shoaibsufi** [comment]
Seems like a good idea - can you show a mock up to Giacomo and I so we can see the idea in action (if it's too onerous then let us know)

Did this answer the question?

**Comment by rgaiacs** [comment]
> can you show a mock up to Giacomo and I so we can see the idea in action (if it's too onerous then let us know)

I did search for libraries last year to edit the PDF and I couldn't find a good solution. I can talk with Giacomo in the coming weeks to see what we can do about it.
