### ISSUE TITLE
Change name of the app

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#153]
I'm asking the people involved in this project so far: @rgaiacs, @shoaibsufi, @npch , @DevasenaInupakutika : since the name we are using, FAT, could raise issues, especially if we open up the project to the wider public, should we take a decision now and rename it?

I propose S(oftwaresustainabilityinstitute)A(dmin)T(ool): SAT

Other suggestions are welcome.

**Comment by npch** [comment]
I don't think SAT helps either, as there's a well-used acronym already in existence that overlaps.

How about looking at this guide:
https://www.software.ac.uk/resources/guides/choosing-project-and-product-names

:-)

**Comment by shoaibsufi** [comment]
It's now LowFAT
