### ISSUE TITLE
TypeError: object of type 'map' has no len() 

### ISSUE THREAD

**Issue by DevasenaInupakutika** [softwaresaved/lowfat#171]
I am getting the above error when running any of the FAT python commands like:

~~~
python3 manage.py migrate
~~~
or

~~~
 python3 manage.py dbbackup --encrypt && python3 manage.py mediabackup --encrypt
~~~~

It seems like issue with python3 and the package `python-social-auth`. I tried upgrading this package but still getting the same error. Also, I looked for this error and tried the python3-openid package but the issue persists. 

Reference: [https://github.com/omab/python-social-auth/issues/439](https://github.com/omab/python-social-auth/issues/439)

**Comment by rgaiacs** [comment]
> I am getting the above error when running any of the FAT python commands like `python3 manage.py migrate`

I ran

~~~
$ conda create -n fat2 python
$ source activate fat2
$ /tmp
$ git clone git@github.com:softwaresaved/fat.git
$ cd fat
$ python -m pip install -r requirements.txt
$ python manage.py migrate
~~~

and I didn't get a error.

I got a error when running

~~~
$ python3 manage.py dbbackup --encrypt && python3 manage.py mediabackup --encrypt
~~~

but it was related with unconfigured `fat/settings.py`.

Can we give more details of the problem you are having?

**Comment by DevasenaInupakutika** [comment]
Yes, I tried in virtual environment and `migrate` works fine. Seems due to some old code dependencies.

**Comment by rgaiacs** [comment]
> Yes, I tried in virtual environment and migrate works fine now. Seems due to some old code dependencies.

:-) Can we close?
