### ISSUE TITLE
On request for funding page, we could use calendar widget to enter dates

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/lowfat#179]

**Comment by rgaiacs** [comment]
@anenadic Thanks for the suggestion. I tried to find a nice calendar widget but failed on this task.

**Comment by rgaiacs** [comment]
I tried https://github.com/nkunihiko/django-bootstrap3-datetimepicker but I'm have some issues:

- https://github.com/nkunihiko/django-bootstrap3-datetimepicker/issues/59
- `Uncaught TypeError: $(...).datetimepicker is not a function`

**Comment by rgaiacs** [comment]
Implemented in #291.
