### ISSUE TITLE
On funding request page, rename budget request cost labels under 'Costs' section

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/lowfat#182]
Budget request travel -> Travel costs
Budget request attendance fees -> Attendance fees
Budget request subsistence cost -> Subsistence costs
Budget request venue hire -> Venue hire
Budget request catering -> Catering
Budget request others -> Other costs

**Comment by npch** [comment]
Also make it clear what certain common things come under 

Subsistence costs (e.g. accommodation and meals)

Attendance fees (e.g. workshop / event registration costs)
