### ISSUE TITLE
On Funding Request page "Extra sponsored" title is confusing

### ISSUE THREAD

**Issue by npch** [softwaresaved/lowfat#190]
Either remove, or rewrite to make it clear what information is required in this field.

**Comment by rgaiacs** [comment]
@shoaibsufi Can you provide me with a new title?

![screencapture-localhost-8000-request-1487157489869](https://cloud.githubusercontent.com/assets/1506457/22972220/a7adba6c-f370-11e6-8661-426f4ccba794.png)

**Comment by npch** [comment]
As a suggestion: "Details of people being sponsored from your Fellowship funds"?

**Comment by rgaiacs** [comment]
Close by #231.
