### ISSUE TITLE
Add name of Fellow to Fund Review

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#193]
Once you open the Fund Review webpage the name of the Fellow is not shown anywhere. It should be visible.

**Comment by rgaiacs** [comment]
# Screenshot proposal

![screencapture-localhost-8000-request-10-review-1486649095220](https://cloud.githubusercontent.com/assets/1506457/22786612/28c4fd26-eed1-11e6-955a-0192a78352a6.png)
