### ISSUE TITLE
Enable administrators to view log of all transactions via dashboard

### ISSUE THREAD

**Issue by npch** [softwaresaved/lowfat#240]
Administrators will require the ability to view a log of all transactions that have happened in lowFAT to identify (for instance) when a claim has been submitted or processed.

This could be done by simply providing a way to display the logged transactions via the dashboard.

**Comment by npch** [comment]
Alternatively, as an interim solution, could we provide admin instructions for accessing this log by other means?

**Comment by rgaiacs** [comment]
Close by #243.
