### ISSUE TITLE
Add invoice option to claim submission

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#242]

**Comment by rgaiacs** [comment]
Just a flag.

**Comment by rgaiacs** [comment]
Create reference number

**Comment by shoaibsufi** [comment]
reference: SSI<number>

e.g. SSI1234abcd

**Comment by rgaiacs** [comment]
Use as reference SSIFxxxx

**Comment by shoaibsufi** [comment]
where x is an alphanumeric

**Comment by shoaibsufi** [comment]
4 alphanumeric give us 36^4 permutations - 1,679,616 possible invoices ... that should be enough ; )

**Comment by rgaiacs** [comment]
Prototype at https://github.com/softwaresaved/lowfat/pull/251.

**Comment by rgaiacs** [comment]
I'm reopening this one since I reverted #251 because it uses [blake2](https://docs.python.org/3/library/hashlib-blake2.html) that is only available on Python >= 3.6.
