### ISSUE TITLE
Add data for historical blog posts for events

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/lowfat#253]
You can get data from Fellows from an author tag search e.g. for Rob Haines - https://www.software.ac.uk/author/robert-haines

It will need time to do manual reconciliation to see if it was linked to the event.

We have time from the Oxford Events team to do this task - just need a bit of training in terms of how to put the data in lowFAT

**Comment by rgaiacs** [comment]
> need a bit of training in terms of how to put the data in lowFAT

@shoaibsufi I sent you instructions by email.

**Comment by rgaiacs** [comment]
I believe this one has been done.
