### ISSUE TITLE
Date shown in US style

### ISSUE THREAD

**Issue by dpshelio** [softwaresaved/lowfat#256]
At least in the dashboard, under "Funding request" I get the start date and end date in `%m/%d/%Y`. I've seen that in the `settings.py` file the date is set up differently
```python
DATE_FORMAT = "l, d F Y" # British English style
```
Maybe this happens because:
 ```python
LANGUAGE_CODE = 'en-us'
```
and when abbreviating it is using the US-way?

**Comment by rgaiacs** [comment]
@dpshelio Thanks for the report. I will talk with @shoaibsufi and @gperu to decide when we are going to update the server.
