### ISSUE TITLE
Document that funding request need be created before submit blog posts

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#260]
In the case that fellows wanted to submit a blog post for an event they organised but we didn't fund it, **does they need to create a funding request?** At the moment **yes**.

@shoaibsufi @npch @SimonHettrick Should we change this in a future release? At the moment it will help us with any future metric, for example, number of events, but it will cost 5 minutes from fellows (to submit the form) and another 5 from us (to process the form).

**Comment by npch** [comment]
What would be the proposed alternative workflow? Fellow submits a blog post and we assign it? We create an event and then the Fellow submits the blog post?
What happens if a blog post is not assigned to an event (I assume that this throws off our metrics, as we're undercounting events)?
