### ISSUE TITLE
Add url of lowFAT instance to emails we receive so we can ignore dev ones

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/lowfat#281]
Example email:

---------- Forwarded message ----------
From: no-reply@software.ac.uk <no-reply@software.ac.uk>
Date: Thu, Mar 9, 2017 at 1:06 PM
Subject: [ssi-fellows-management] We have a new funding request pending your review
To: Software Sustainability Institute <fellows-management@software.ac.uk>

Hi,

We received a new funding request from
Giacomo Peru for
CW17.

Please visit /request/159/review to review it.

---
LowFAT

**Comment by shoaibsufi** [comment]
What it should look like:

---------- Forwarded message ----------
From: no-reply@software.ac.uk <no-reply@software.ac.uk>
Date: Thu, Mar 9, 2017 at 1:06 PM
Subject: [ssi-fellows-management] We have a new funding request pending your review
To: Software Sustainability Institute <fellows-management@software.ac.uk>


Hi,

We received a new funding request from
Giacomo Peru for
CW17.

Please visit /request/159/review to review it.

---
LowFAT **(dev.fellows.software.ac.uk)**

**Comment by shoaibsufi** [comment]
Does not need to be in bold - but just highlighting the addition

**Comment by rgaiacs** [comment]
This was a issue at the configurations of the developer server. This is fixed now.
