### ISSUE TITLE
Attribution of events expenditure to the right funds

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#283]
There is something wrong in the way lowFAT is calculating the total of funds used from a personal fellowship grant.

Looks like that some expenditure that should be from core funds is coming from fellowship.

I'm not sure where the problem is here. Maybe when submitting the funding request, the cost were associated by default to the personal grant.

**Comment by gperu** [comment]
If #284 is implemented, I could correct the wrong calculation in Robitaille's case.

**Comment by rgaiacs** [comment]
This implemented at #287.
