### ISSUE TITLE
Update Blog post status

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#304]
At the moment we have

~~~
BLOG_POST_STATUS = (
    ('U', 'Unprocessed'),
    ('R', 'On Google Drive (for review)'),
    ('L', 'On pipeline to be published'),
    ('P', 'Published'),
    ('D', 'Declined'),
    ('O', 'Out of date'),
)
~~~

We should change to

- Submitted

  This is the status after we receive the blog post draft.
- Assign to reviewer

  Blog posts will be assign to one of our staffs to be reviewed.
- Waiting proofread

  After the review,  the blog post draff need to be proofread by our community officer.
- On pipeline to be published

  After the proofread, the blog post draft will be publish by the community officer.
- Published

  The blog post draft is published and have a URL at the website.
- Declined

  For blog posts submited by mistake.
- Out of date

  For blog posts that wait for long to be publish for any reason.

**Comment by selina-aragon** [comment]
For "waiting to be proofread", could we add that the comms officer will proofread it as well? I often end up making edits, even if minor, to most of the posts. It'd be good to let the authors know that their text will be proofread by two people before going on the pipeline to be published.

**Comment by edwardsmith999** [comment]
I was going to create a separate issue but I think this comes under blog status. It would be great to be able to delete/edit blogs while still in Submitted status. I made the mistake of attempting to use Microsoft my.sharepoint.com and now have two version of the same blog, one dead link and one to google docs (which works). Also, the ability to add a short (~200 word) piece of optional metadata for the reviewers would be useful. I've submitted two separate blog posts at the same time and wanted to make this clear.

**Comment by rgaiacs** [comment]
@edwardsmith999 Thanks for the feedback! 

> It would be great to be able to delete/edit blogs while still in Submitted status.

I added this to the list of features: https://github.com/softwaresaved/lowfat/issues/315.

>  I made the mistake of attempting to use Microsoft my.sharepoint.com and now have two version of the same blog, one dead link and one to google docs (which works).

I removed the my.sharepoint.com.

> Also, the ability to add a short (~200 word) piece of optional metadata for the reviewers would be useful.

I added it to the list of features: https://github.com/softwaresaved/lowfat/issues/316.
