### ISSUE TITLE
Advance booking in expense submission

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#355]
Sometime Fellows ask us to pre-book travel items for them. We need to add these expenses to their funding request, along with their expense claims and invoices. A third option should be implemented whereby the admin user can submit an advance booking.

**Comment by gperu** [comment]
As discussed, a tick-box "Advance booking" will do.

We are evolving to a system where there three types of expense submissions:
- claim
- invoice
- advance booking

**Comment by rgaiacs** [comment]
My suggestion of workflow is describe on the diagram below:

![img_20170719_163324](https://user-images.githubusercontent.com/1506457/28375778-4c326288-6ca0-11e7-9591-c4bf7e8d1f77.jpg)

The changes that need to be done on the code are

1. add the check box for "advanced booking" and
2. support to multi attaches.

**Comment by gperu** [comment]
It looks good to me.
Thanks
