### ISSUE TITLE
Multiple currency totals

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#360]
On the expense submission form it would be useful to have the possibility to submit multiple totals for different currencies.

**Comment by rgaiacs** [comment]
@gperu Thanks for the suggestion.

We need to talk about this so that it helps you **and** the fellows.

# Screenshot suggestion

![lowfat-currency](https://user-images.githubusercontent.com/1506457/28262448-e8addcf4-6ada-11e7-85d8-cb50d2c2721b.png)

**Comment by rgaiacs** [comment]
@gperu we need to talk about currency exchange before implement this.
