### ISSUE TITLE
MultipleObjectsReturned

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#362]
~~~
MultipleObjectsReturned at /request/X/expense/Y/review
get() returned more than one Expense -- it returned 2!
~~~

**Comment by rgaiacs** [comment]
This is related with https://github.com/softwaresaved/lowfat/blob/master/lowfat/views.py#L505.

**Comment by shoaibsufi** [comment]
A touch more description would be useful - e.g. why is this a problem and what the behaviour should be.

**Comment by rgaiacs** [comment]
This issue is related with https://github.com/softwaresaved/lowfat/blob/master/lowfat/views.py#L500. Since we have something like `https://fellows.software.ac.uk/request/X/expense/Y/`, where `X` is the request number id and `Y` is the relative expense number id, instead of `https://fellows.software.ac.uk/expense/Z/`, where `Z` is the expense number id, we are trying to access the information using a "mutable" information. Because at some point we had two entries on the database with the same tuple `(X, Y)`, Django failed since the method that we use only returns one entry. I will need to inspect the database backup to know more.
