### ISSUE TITLE
Show Fellow name in summary tables

### ISSUE THREAD

**Issue by npch** [softwaresaved/lowfat#380]
On the dashboard for administrators, when funding requests or expense claims are listed in the summary tables, it would be useful to include a column showing the Fellows name.

Note this is not required for the summary of blog posts as the name of the Fellow is included in the Blog field.

**Comment by rgaiacs** [comment]
Screenshot

![screencapture-localhost-8000-dashboard-1504104066629](https://user-images.githubusercontent.com/1506457/29878190-c3944da4-8d99-11e7-8a1b-ad0d3ecbfcae.png)
