### ISSUE TITLE
Updating of working needed for promoting events

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/lowfat#425]
One of the Fellow said:

'Also I ticked the "can we promote your event" but it's not really my event, but if it's relevant I am happy to advertise that I'm going/ about the event?'

Perhaps we should ask them 'Can we promote your involvement in this event?'

**Comment by rgaiacs** [comment]
> Perhaps we should ask them 'Can we promote your involvement in this event?'

We are asking it. :-)
