### ISSUE TITLE
Replies to lowFAT emails.

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#442]
We can send emails to users from lowFAT. Can users reply from their client and their reply go back to lowFAT? That would be useful both for the user and the admin.

**Comment by rgaiacs** [comment]
> Can users reply from their client and their reply go back to lowFAT?

Not at the moment. Implement this is quite challenge when you don't control your email server.

**Comment by rgaiacs** [comment]
We could use http://django-mailbox.readthedocs.io/ but we need to get one email account from the university.

**Comment by rgaiacs** [comment]
This is pending creating of email box in Edinburgh.
