### ISSUE TITLE
Problem with some of the data?

### ISSUE THREAD

**Issue by marioa** [softwaresaved/lowfat#455]
Events that have lasted more than 14 days:

| event_id | event_start_date | event_end_date | dt  |
|:--------:|:----------------:|:--------------:|:---:|
|   244    |    2017-12-25    |   2018-02-02   | 39  |
|   229    |    2017-10-23    |   2017-11-30   | 38  |
|   226    |    2017-10-01    |   2018-03-31   | 181 |
|   171    |    2017-07-03    |   2017-09-03   | 62  |
|   192    |    2017-01-02    |   2017-03-02   | 59  |
|   198    |    2016-01-15    |   2017-01-14   | 365 |
|   116    |    2015-11-09    |   2015-11-30   | 21  |
|   106    |    2015-09-16    |   2015-10-02   | 16  |
|    23    |    2013-07-28    |   2013-08-23   | 26  |

**Comment by rgaiacs** [comment]
Events can last more than 14 days.
