### ISSUE TITLE
Surely the same person?

### ISSUE THREAD

**Issue by marioa** [softwaresaved/lowfat#456]
| fellow_id | fellow_fornames | fellow_surname   |
|----------:|:----------------|:-----------------|
|       414 | ----            | ----          |
|       358 | ----      | ----          |

**Comment by rgaiacs** [comment]
We record applications so is possible that some people are duplicated because they applied more than once.

**Comment by shoaibsufi** [comment]
https://docs.google.com/spreadsheets/d/10wuU30RQ_DZtc9BmRU1ZS5VZ7WI4zQiDesgMK9sL0OE/edit#gid=1848575013 has been updated
