### ISSUE TITLE
Another duplicated person

### ISSUE THREAD

**Issue by marioa** [softwaresaved/lowfat#457]
| fellow_id | fellow_fornames | fellow_surname   |
|----------:|:----------------|:-----------------|
|       258 | ----         | ----           |
|       345 | ----         | ----           |

**Comment by rgaiacs** [comment]
As mentioned in #456,

> We record applications so is possible that some people are duplicated because they applied more than once.

**Comment by shoaibsufi** [comment]
258 is when Rebecca was an applicant who did not make it as a Fellow me thinks.

345 would be the 2nd application where she did make it


sqlite> select forenames, surname from lowfat_claimant where id in (258, 345) ;
Rebecca|Wilson
Rebecca|Wilson

select id, forenames, surname from lowfat_claimant where id in (258, 345) and fellow=1 ;

**Comment by shoaibsufi** [comment]
I have updated the query - this should not happen now - https://docs.google.com/spreadsheets/d/10wuU30RQ_DZtc9BmRU1ZS5VZ7WI4zQiDesgMK9sL0OE/edit#gid=1848575013 has been updated
