### ISSUE TITLE
[GDPR] Consent checkboxes

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#464]
https://techblog.bozho.net/gdpr-practical-guide-developers/ says

> “I accept the terms and conditions” would no longer be sufficient to claim that the user has given their consent for processing their data. So, for each particular processing activity there should be a separate checkbox on the registration (or user profile) screen. You should keep these consent checkboxes in separate columns in the database, and let the users withdraw their consent (by unchecking these checkboxes from their profile page – see the previous point). Ideally, these checkboxes should come directly from the register of processing activities (if you keep one). Note that the checkboxes should not be preselected, as this does not count as “consent”. Another important thing here is machine learning/AI. If you are going to use the user’s data to train your ML models, you should get consent for that as well (unless it’s for scientific purposes, which have special treatment in the regulation). Note here the so called “legitimate interest”. It is for the legal team to decide what a legitimate interest is, but direct marketing is included in that category, as well as any common sense processing relating to the business activity – e.g. if you collect addresses for shipping, it’s obviously a legitimate interest. So not all processing activities need consent checkboxes.

# TODO

- [ ] define what "legitimate interest" is. @npch and @SimonHettrick, could you help?
- [ ] create a page documenting "legitimate interest".

**Comment by npch** [comment]
@rgaiacs I'm getting some guidance on this, but I think the legitimate interest would be "fulfilment of contract" - basically for lowFAT, we are engaging in a contractually bound agreement with the Fellows, and lowFAT is the way of doing this. Therefore this is not using the more general "consent" criteria.

I'll be providing details of what you will need to do in the next week or so.

**Comment by npch** [comment]
More generally, this means we need to put some information into the documentation about how others might use lowFAT if they are installing themselves.

**Comment by rgaiacs** [comment]
#476 and #475 is related with this one.

**Comment by rainsworth** [comment]
Check with Neil to see if there is anything that needs to be checked.
