### ISSUE TITLE
Ability to produce/export financial reports

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#482]
- Total amount of expenditure
- Total expenditure by grant heading
- Average expenditure by fellow
- Average expenditure by fellow and grant heading

**Comment by rgaiacs** [comment]
We will use data URIs as mentioned in https://stackoverflow.com/a/3665147/1802726 to generate the CSV file to download.

**Comment by rgaiacs** [comment]
@gperu softwaresaved/lowfat#484 implements

![screenshot from 2018-06-26 16-15-17](https://user-images.githubusercontent.com/1506457/41922058-2ca9595c-795c-11e8-9efa-62d865da8f18.png)

- Total expenditure by grant heading

  I'm looking on how to better implement this.
- Average expenditure by fellow

  Could you translate this to math equations?
- Average expenditure by fellow and grant heading

  Could you translate this to math equations?

**Comment by rgaiacs** [comment]
I'm closing this based on softwaresaved/lowfat#484.
