### ISSUE TITLE
Simplification of expenses statuses

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#483]
Submitted
Processing
Passed to finance (or something like this)

... are the only statuses needed. If @rgaiacs is happy to do the change we can discuss how to handle the past records in the DB.

**Comment by rgaiacs** [comment]
> happy to do the change

Yes.

> we can discuss how to handle the past records in the DB.

Send me a table of what should be the new statuses for past records and I will handle it.

**Comment by rgaiacs** [comment]
@gperu the expenses statuses that we have now are

- Not submitted yet
- Submitted (awaiting processing)
- Administrator checking
- Authoriser checking
- Approved (submitted to finance)
- Finished
- Rejected
- Remove

I need to know for each one what will be the status if we only have

- Submitted
- Processing
- Passed to finance (or something like this)

**Comment by gperu** [comment]
- Not submitted yet => (I don't know, maybe just not bother about non-submitted expenses)
- Submitted (awaiting processing) => Submitted
- Administrator checking => Processing
- Authoriser checking => Processing
- Approved (submitted to finance) => Approved
- Finished => Approved
- Rejected (I don't know, it's not a real case, so maybe just eliminate this status?)
- Remove (I suggest to elimitate this status too unless removing an expense from this page is considered a useful case).

Is this all right?
