### ISSUE TITLE
Add location the event will be held at for requests

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#489]
@marioa said that

> Looking through the event data it would be good to add the location that fellows are attending - it would make some nice visual representation of where fellows have been.

**Comment by rgaiacs** [comment]
Have a look at https://github.com/erdem/django-map-widgets and https://www.gyford.com/phil/writing/2017/03/16/django-admin-map/ to make easy for people to provide the correct information to us.

**Comment by marioa** [comment]
Looks really cool - what information does it store? Long/Lat? Does it also store the location name?

**Comment by rgaiacs** [comment]
We need to pay to use Google Maps API (probably because Google want to make money out of Uber et al.) so I'm looking at alternatives.
