### ISSUE TITLE
Upload additional documents

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#494]
If we need to add a document (e.g. a missing receipt) to a pdf claim on lowFAT, we currently have to replace the existing pdf with a new one which has the additional document. 

It would be easier if we could just upload additional documents to the exiting one.

**Comment by rgaiacs** [comment]
> It would be easier if we could just upload additional documents to the exiting one.

I have some ideas that I'm testing.

**Comment by rgaiacs** [comment]
@gperu in the short future we can talk about https://github.com/softwaresaved/lowfat/pull/500 and see if it is suitable for your workflow.
