### ISSUE TITLE
Check blogpost before processing expenses.

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#495]
I often forget to check if a blogpost is in before processing an expenses claim. Could we enginner something that prevents to go ahead without checking on the blogpost?

**Comment by rgaiacs** [comment]
> Could we enginner something that prevents to go ahead without checking on the blogpost?

Yes. We need to chat about how to do it.

**Comment by rgaiacs** [comment]
@gperu I noticed that on the expense review form we have some information about the blog post submission.

![Blog post submission information](https://user-images.githubusercontent.com/1506457/46657033-47d63e00-cba7-11e8-9a45-a88c79d77f6b.png)

I need to acknowledge that it isn't very visible. What do you think would be a good workflow? Some options

1. Add a big warning text at the begin of the form.
2. Raise a confirmation request after send information to be saved on the database.

**Comment by rgaiacs** [comment]
Implemented.
