### ISSUE TITLE
Asking about success

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/lowfat#496]
At Event request time it would help us if we understood what the Fellow thought successful outcomes and outputs or other things were for the event.

This helps them understand purpose behind activities and helps us understand and expand upon success criteria and feed into the Communities of Practice work potentially.

@rgaiacs we can talk about the design of this - perhaps late October 2018 onwards.

**Comment by rgaiacs** [comment]
> we can talk about the design of this - perhaps late October 2018 onwards.

Yes. Any time.

**Comment by shoaibsufi** [comment]
from https://fellows.software.ac.uk/request/

after Additional info:

Successful outputs and outcomes:

Please specify what the successful outputs (what maybe be produced) and outcomes (what change it could lead to) would be for you attending/organising this event. These can include learning goals being met, collaborations, reports etc.

**Comment by shoaibsufi** [comment]
On https://fellows.software.ac.uk/blog/

after URL of blog post draft

These are the successful outputs and outcomes you said might happen from your participation in this event. 
<text>
What outputs were produced and which outcomes did your participation lead to.

**Comment by rgaiacs** [comment]
Implemented on #525.
