### ISSUE TITLE
Same look as software.ac.uk

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#506]
Would be great to have the same look as software.ac.uk

# Screenshots

fellows.software.ac.uk

![screenshot from 2018-11-13 09-44-21](https://user-images.githubusercontent.com/1506457/48404768-ef0b3f80-e728-11e8-9e15-68a4fe3608db.png)

software.ac.uk

![screenshot from 2018-11-13 09-44-47](https://user-images.githubusercontent.com/1506457/48404790-f6324d80-e728-11e8-9675-bc4eba610c9a.png)

**Comment by selina-aragon** [comment]
I'm not sure I understand this ticket. @rgaiacs is this about Lowfat looking like the SSI website? If so, do you need any input from me?

**Comment by rgaiacs** [comment]
> If so, do you need any input from me?

No.
