### ISSUE TITLE
Incorrect total expense calculation

### ISSUE THREAD

**Issue by Benjamin-Lee** [softwaresaved/lowfat#536]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/13618205/55196646-61376a80-5186-11e9-8776-198c2edf3b15.png">

As can be seen in the screenshot, the total expenses appear to be including expense claim #2,  which was a duplicate and was deleted. Either way, the total expense is not correct.

**Comment by rgaiacs** [comment]
Thanks for the issue. We will fixed it in the next 2 weeks

**Comment by rgaiacs** [comment]
This should be fixed now.
