### ISSUE TITLE
Review default email when funding request is archived

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#538]

**Comment by rainsworth** [comment]
Currently states "Archived - contact claimants-management@software.ac.uk if need"

Should be "Archived - contact fellows-management@software.ac.uk if needed"

**Comment by phillybroadbent** [comment]
The message now says 'Archived - contact fellows-management@software.ac.uk if needed' in the funding request and expenses tables on the dashboard and funding request detail page. Is there anywhere else that this needs editing @rainsworth ?

**Comment by rainsworth** [comment]
Thank you @phillybroadbent! Can you just check if it needs to be updated for the blog post table as well? I think that would be the last instance.

**Comment by phillybroadbent** [comment]
I just checked and the blog post table contains the email of the blog reviewer rather than the email specified above so it doesn't need changing there.
