### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by agbeltran** [softwaresaved/lowfat#559]
When trying to upload an expense claim, the systems gives a 500 server error, however the claim systems to have been uploaded anyway.

Steps:
1. select an existing funding request
2. select submit expense claim and follow the procedure to upload the PDF file
3. when submitting, the system gives a 500 error
4. going back to the existing funding request, it is possible to see the uploaded files

**Comment by rgaiacs** [comment]
The bug is on https://github.com/softwaresaved/lowfat/blob/master/lowfat/views.py#L741:

```
    if formset.is_valid():
        expense = formset.save()
        messages.success(request, 'Expense saved.')
        if not formset.cleaned_data["not_send_email_field"]:
            new_expense_notification(expense)
        return HttpResponseRedirect(
            reverse('expense_detail_relative', args=[expense.fund.id, expense.relative_number,])
        )
```

The `new_expense_notification()` call fail and give you the 500 error.
