### ISSUE TITLE
Set blog post count to 0 for mandatory events

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/lowfat#563]
If an event request is for a 'mandatory' event it should set the blog post count to 0 (if they untick it - it should set it back to 1).

This is because for events like the Fellows Inaugural and Collaborations Workshop we don't require Fellows to write a blog post but they can if they wish.

This is the current policy - May 2019

**Comment by rainsworth** [comment]
This is no longer required because it doesn't automatically approve these events anymore.
