### ISSUE TITLE
lowFAT buggy on Firefox?

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#564]
Reported from Sorrel Harriet:
"LowFat seems to be a bit buggy in Firefox. I submitted a blog draft and it appeared as 4x drafts on my dashboard. I removed one, it removed all of them...so I'll resubmit. Just in case anyone wonders what on earth is going on there!"

**Comment by jag1g13** [comment]
Not sure why 4 copies were visible, but I've managed to replicate getting 2 copies.

If a (non-staff) user is both the author and a co-author of a blog post, the SQL query constructed by Django returns two copies of the same blog post.  This would not normally happen, but each OR in the filter is being applied on a different table join, so Django does not realise that the two results are the same thing.

Explicitly asking Django to perform deduplication resolves this issue.
