### ISSUE TITLE
Reply-to address for lowfat communications

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#571]
Change so that the "Reply-to" address is to the person who sent the email and Cc fellows-management.

It currently automatically replies to fellows-management:

![Screenshot 2019-09-26 at 15 17 26](https://user-images.githubusercontent.com/10600877/65696263-d110aa00-e070-11e9-8d23-669f1c55edc1.png)

**Comment by jag1g13** [comment]
Should be resolved in 8030c2e - will deploy during next patch window
