### ISSUE TITLE
Bug: auto-approval funding requests do not appear under All/Approved funding requests

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#572]
When claimants (fellows) submit a funding request for under some amount of money (I think ~£250?) and tick the box for "Is this related with Fellows face to face selection meeting, Fellows inaugural meeting or Collaborations Workshop?" - the request is approved automatically. 

However, these auto-approved funding requests do not appear on the admin dashboard under either the All nor Approved tabs for funding requests.

**Comment by jag1g13** [comment]
Related bug report from user:

> My funding request has been approved but does not appear in the drop down "Choose approved funding request" menu for making the expenses claim.

Emma Rand - Fellows Inaugural Meeting 2020
