### ISSUE TITLE
Use of deprecated authentication method in GitHub API

### ISSUE THREAD

**Issue by npch** [softwaresaved/lowfat#577]
We received the following warning about use of a deprecated parameter:

> On February 6th, 2020 at 16:27 (UTC) your application (lowFAT) used an access token (with the User-Agent python-requests/2.21.0) as part of a query parameter to access an endpoint through the GitHub API.

> https://api.github.com/user

> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by jag1g13** [comment]
This is in the process of being fixed upstream - I'll keep an eye on this and update as soon as they release.

See python-social-auth/social-core#428

**Comment by jag1g13** [comment]
@rainsworth @shoaibsufi for status update

The upstream fix has been stalled for a couple of weeks now - a discussion has begun about providing more direct support to the project, which appears to have only one maintainer.

The [deprecation timeline](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) says that the current authentication method will stop working temporarily on 30th September and 28th October, then permanently from 13th November this year.

This gives us a reasonable amount of time for this to be fixed, but if still not fixed upstream by then, I can put in a workaround at our end.
