### ISSUE TITLE
Add Mastodon social network to fellow profiles

### ISSUE THREAD

**Issue by jezcope** [softwaresaved/lowfat#578]
It would be great to be able to add a link to my Mastodon profile, <https://digipres.club/@petrichor>. Mastodon is a federated microblogging platform, with users on any server able to follow users on any other. Profile links are of the form `https://<server>/@<username>`.

Thanks!

**Comment by rainsworth** [comment]
FYI: Updated the website (which is not linked to lowfat): https://www.software.ac.uk/about/fellows/jez-cope
