### ISSUE TITLE
Updates to links on expenses claim form

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#580]
Claim form: https://fellows.software.ac.uk/expense/

- Change the link to the guidelines to: https://drive.google.com/open?id=1oddJAqzf7wIrzj7r3qPQ-ijoZzPcILQ9
- Add a direct link to the claim form, as many Fellows don’t actually fill it out: https://drive.google.com/open?id=1muv__x8fhiaGw2hI81sytXTgFqnOsVGl

**Comment by rainsworth** [comment]
On the [Expense Claims webform](https://fellows.software.ac.uk/expense/), please replace: 
> Fellowship Programme's terms and conditions applies to your request. Please follow the guidelines at How to apply for, and claim, expenses section of Fellowship Programme's terms and conditions.

with: 
> Before submitting your expense claim:
> 1. Please follow the [Guidelines for reimbursement of expenses from the Software Sustainability Institute](https://drive.google.com/file/d/1oddJAqzf7wIrzj7r3qPQ-ijoZzPcILQ9/view).
> 2. You MUST fill out and attach the [University of Edinburgh Payment for Non-Staff/Student Expenses form](https://drive.google.com/file/d/1muv__x8fhiaGw2hI81sytXTgFqnOsVGl/view) along with your receipts to your expense claim.
> 3. The [Fellowship Programme Terms and Conditions](https://www.software.ac.uk/fellowship-programme/2020/terms-and-conditions) and the [University of Edinburgh Finance Expenses Policy](https://drive.google.com/file/d/1wjCD2anwNGgDqee_2dm1C0moPrqxNbju/view) apply to your request.
