### ISSUE TITLE
Add event reporting view

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#581]
Would be useful if lowfat could handle reporting of events (funding requests)
- Show which events are organised vs attended, domain vs cross-cutting per date range
- Filter out SSI organised/mandated
- Format: normally stuck into a slide (an image would not be useful)
- Couple of tables/data vis presenting data

**Comment by shoaibsufi** [comment]
An example of this hand crafted for the Fellows 2020 inaugural is below - original slide set is here - https://docs.google.com/presentation/d/18OxN-QxRPAwFmnQTmxyCF8-3Kh11dH_a/edit#slide=id.p7 (slide 7)

So it's useful to show numbers also in a cross-tabulation (as done in the slide).

![Screenshot 2020-06-05 11 54 56](https://user-images.githubusercontent.com/473827/83868939-a4df1a00-a723-11ea-8058-13f20421acb2.png)

**Comment by phillybroadbent** [comment]
Event reporting view created as shown in the image above.  Only staff can access.
