### ISSUE TITLE
Replace Crispy Forms with vanilla Django forms

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#590]
All forms within LowFAT need to be replaced with vanilla Django forms, using their own template file.
This will make it much simpler to make minor changes and allow us to remove a dependency which has caused problems in the past.

See: https://github.com/softwaresaved/lowfat/blob/master/lowfat/forms.py

**Comment by jag1g13** [comment]
In retrospect it may only be necessary to redo how crispy forms layouts are described. See https://stackoverflow.com/questions/13098954/use-crispy-form-with-modelform for an example of a minimal ModelForm use.

Either solution should work fine

**Comment by PipGrylls** [comment]
Actively supported and no conflicts so not fixing this for now

See for details:

https://github.com/django-crispy-forms/django-crispy-forms
> django-crispy-forms supports Django 2.2, 3.1 and 3.2 with Python 3.6+.
