### ISSUE TITLE
Don't squash people's faces

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#594]
Profile images are currently resized to ensure they are square - this squashes the images if they weren't already square.
Probably should crop first, then resize.

**Comment by elena-kolomeets** [comment]
Maybe this tool could help: [Django-Imagekit](https://github.com/matthewwithanm/django-imagekit)

**Comment by jag1g13** [comment]
Thanks! That sounds useful and I haven't heard about it before - I'll have a proper look this week

**Comment by PipGrylls** [comment]
This is fixed on branch django-v3-port: https://github.com/softwaresaved/lowfat/tree/fb0927075aa89a845ff4408b6bf3bde7341f32d1

Thank you Elena for the Imagekit suggestion it was exactly what we needed.
