### ISSUE TITLE
Validate email address list entered into admin Constance page

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#595]
> "Hi - just submitted a blogpost there now on lowFAT but got Server Error (500) - can you see my submission ok?"

> His submission has come through quite a few times, so I don't know if the error is a result of last week's updates
> (I also didn't receive any email notifications of lowfat submissions like I normally would)

**Comment by rainsworth** [comment]
The error also happens when submitting a funding request (I imagine the error occurs for all submissions, and is linked to not sending email notifications of submissions to lowfat).

**Comment by jag1g13** [comment]
This should be resolved now - a look at the logs showed that this was due to a config error when adding a new email address to the list of approvers.

To prevent this in future, the admin page for Constance should validate the list of email addresses
