### ISSUE TITLE
Replace deployment with Ansible

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#597]
The current deployment works well for updates, but is not obvious how to deploy to production from scratch.
We can reuse Ansible deployment scripts from our other Django projects .

**Comment by PipGrylls** [comment]
Do you still want this now it is dockerised?

**Comment by jag1g13** [comment]
Ideally the Docker setup and starting the containers will be done with Ansible, though this is less important now that we're using Docker. I'd like to leave this open, but I'm not too worried that I didn't get time to do it this sprint.

**Comment by OscarSeip** [comment]
Closing this issue for now, already moved to Wont Fix.
