### ISSUE TITLE
Split existing models and views modules into multiple files

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#598]
Both models.py and views.py are over 1k lines and contains all of the models / views in a single module.
Splitting each of these up into a package containing modules for all of the major models will greatly improve readability.

e.g. `models/` and `views/` could both contain:
- `claimant.py`
- `fund.py`
- `expense.py`
- `blog.py`

**Comment by elena-kolomeets** [comment]
Hi! I would like to help with this issue. Did I understand it right that instead of `models.py` and `views.py` you would like to have "models/" and "views/" folders with the separate files for every single model and view function? Of course that would also need some changes in `admin.py`, `urls.py` where the models/functions are called.

**Comment by jag1g13** [comment]
Hi @elena-kolomeets , thanks for your offer of help with this issue!

How I imagined this would work is that instead of `models.py` we'd have a directory `models/` containing a Python module for each major model, e.g. `claimant.py`, `fund.py`. Each of these modules would contain the model class, plus any supporting code it needs, e.g. `claimant.py` would also contain all the choices tuples for the attributes of Claimant.

If we moved all of these into separate files we shouldn't need `models.py` anymore. And the same setup for the views.
It's also possible to import all of the models / views from the new files into `models/__init__.py` / `views/__init__.py` which should mean that references to them in the rest of the code don't need to be changed.

If you have any suggestions for alternative approaches though, I'd be very happy to discuss them.

The reason we want to do this is we're planning a big refactor to update to the latest version of Django and replace a load of old code. If these files are tidied up, then it will be easier to do the next steps.

**Comment by elena-kolomeets** [comment]
Oh I didn't know about this option with `/__init__.py`, then these files will contain something like that: `from . import claimant.py, fund.py ...` ?  Please correct me if I'm wrong.
I am relatively new to Django but let this not scare you, I will try my best while working with this issue. And if this contribution turns out to be successful I would be happy to help more.
Then if it's OK with you I will fork the repo, push my changes to a separate branch called "split-models-views" and create a pull request with the number or the issue when it's done :)

**Comment by jag1g13** [comment]
Yes, that sounds good to me, we were all new at some point. Please let me know if there's anything you need help with.

For the `models/__init__.py`, you can do something like:

```python
# file: models/__init__.py
from .claimant import *
from .fund import *
...
```

Then in the rest of the code you should be able to do `from models import Claimant` as we have at the moment.

**Comment by elena-kolomeets** [comment]
Ah right that's what I meant but remembered it wrong, oops. Then I'll get to it, thank you for your support!

**Comment by elena-kolomeets** [comment]
Hi James! I just wanted to tell you that I finished splitting `models.py` files, you can see the commit with the new files [here](https://github.com/elena-kolomeets/lowfat/commit/fe96e7a812c33a8c988999686ff545473c07a2a2).

There was a little problem when I tried to delete the initial `models.py` file: PyCharm told me there 2 usages of the files that did not make it safe to delete it, they are in migrations file: `lowfat/migrations/0149_add_fund_approval_chain.py` in lines 20 and 25 (you can see both usages on the screenshot below).

I did not delete the file. Should I change the reference to `ApprovalChain class` which is now in `models/fund.py` in this file manually and then delete `models.py?` Or should I do anything at all?

<img width="945" alt="conflict_deleting_models_py" src="https://user-images.githubusercontent.com/70906574/100131284-210d1b80-2e84-11eb-8749-a9fad07f3219.PNG">

**Comment by jag1g13** [comment]
Hi Elena, yes, if that's the only reference left to the old `models.py` file, it should be safe to delete.

Because you've added the imports to `models/__init__.py` you shouldn't need to change the references in the migration file. I think that's just PyCharm being confused because it can't tell you've moved the code.

**Comment by elena-kolomeets** [comment]
I opened a pull request and checks showed that I messed up the import statements order (sorry), working on it now.

**Comment by jag1g13** [comment]
No worries, the checks are there to help people with things like that. The common convention is that the order is:
- core Python modules (e.g. `random`, `pathlib`)
- things from the framework (e.g. anything Django)
- other dependencies you've installed
- your own modules
with each section in alphabetical order.

I think our checks are probably a bit too strict at the moment, but have too many exceptions to allow the old code to pass - that's something I'm going to work on in December.

The list of commands that gets run to test a pull request is in https://github.com/softwaresaved/lowfat/blob/master/.github/workflows/lowfat.yml. So you can test this on your own computer using `python -m pylint lowfat` if you want to.

**Comment by elena-kolomeets** [comment]
Thank you for the explanation! 
I ran the tests and now there were only 5 errors connected with ForeignKey (no-member). I saw comments on other lines disabling this error, so I added the same comments `(# pylint: disable=no-member)` to the lines where pylint was throwing this error. Now there are no issues (10/10). Was it right to do so? 
If yes, I will push the changes to my branch. I'm not sure though how to reflect them in the PR (open a new one?)

**Comment by jag1g13** [comment]
The PR should be linked to the branch in your fork, so when you push the changes to your branch it should update the PR and rerun the tests.

Yes, if the error was disabled elsewhere I think it's safe to disable it here - that's something I can check before I merge the PR
