### ISSUE TITLE
Review of dependencies

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#617]
Almost all are out of date, several have been discontinued, several have not been formally discontinued but have had no recent development.

Dependency list as of 2021-06-04 is:

```
django~=2.0.0
django-constance[database]~=2.5.0
django-countries
django-tagulous
django-crispy-forms<1.9
django-datetime-widget
django-dbbackup>=3.2.0
django-extensions
django-pandas
django-picklefield<=2.1.0
django-settings-export
django-simple-history>=1.9.0
django-imagekit>=4.0.2
geopy<=1.19.0
html2text~=2020.1.16
markdown~=3.3.3
matplotlib
numpy
pandas~=1.1.5
pylint>=1.8.2
pylint-django>=0.9.0
pypdf2~=1.26.0
python-gnupg
social-auth-app-django~=3.1.0
social-auth-core~=3.3.1
# Report
jupyter
ipython
# Test
django-autofixture
# Visualise the relationships of Django models
pyparsing
pydot
nbformat~=5.0.8
nbconvert~=6.0.7
```

**Comment by jag1g13** [comment]
(edit this comment to make changes to these lists)

To drop:
- jupyter
  - If we need locally runnable analytics, that's a separate project
- ipython
- pylint
  - Previous linting had exceptions everywhere - move to flake8 and remove exceptions
- pylint-django
- pyparsing
- pydot
  - Maybe a dev dependency?...
- nbformat
- nbconvert
- django-autofixture
  - Not updated in 4+ years - dead
  - Included in `settings.py` but never actually used?

To replace:
- django-tagulous
  - Caution - no longer maintained but probably not easily replaceable - low priority

**Comment by PipGrylls** [comment]
Requiremnts now:

django~=3.2
django-constance[database]~=2.5.0
django-countries
django-crispy-forms
django-datetime-widget
django-dbbackup>=3.2.0
django-extensions
django-pandas
django-picklefield>=3.0.0
django-settings-export
django-simple-history>=1.9.0
django-tagulous==1.1.0
django-imagekit>=4.0.2
geopy<=1.19.0
html2text~=2020.1.16
markdown~=3.3.3
pandas~=1.1.5
pypdf2~=1.26.0
python-gnupg
social-auth-app-django~=3.1.0
social-auth-core~=3.3.1

**Comment by PipGrylls** [comment]
cec6cd92320d7471eca91368ea1f75bcdd0e75f3
