### ISSUE TITLE
Text clipping in thin and long window

### ISSUE THREAD

**Issue by PipGrylls** [softwaresaved/lowfat#618]
![Screenshot 2021-06-10 at 09 55 18](https://user-images.githubusercontent.com/22835635/121496093-0f2f3800-c9d2-11eb-80cf-b76ef92c4395.png)

**Comment by PipGrylls** [comment]
This was scrolled down as far as the browser would go.

**Comment by phillybroadbent** [comment]
To prevent this happening, more padding has been added to the footer while migrating to bootstrap 5.
