### ISSUE TITLE
View of justification information in funding requests for Fellows/claimants

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#631]
When Fellows access their submitted funding requests (https://fellows.software.ac.uk/request/#), they are unable to view the Justification, Success and Additional information that they inputted into the form. This issue requests that all submitted information should be viewable to the Fellow who submitted it.

Also, the row header "Justication" should be "Justification".

**Comment by PipGrylls** [comment]
@phillybroadbent 
- [ ] Find and Fix the Typo
- [ ] Understand how the view displays the information
- [ ] Propose adjustment to the view and associated HTML

**Comment by phillybroadbent** [comment]
Fixed typo.  Edited fund_detail.html to allow a claimant to see the justification, success, and additional information related to their funding request.
