### ISSUE TITLE
Add reply-to email somewhere

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#636]
When Fellows receive an email from lowFAT they cannot reply directly, we know that. Therefore they tend to email Giacomo directly. We should make it clear they should email admin@software.ac.uk.

**Comment by jag1g13** [comment]
Set 'reply-to' header on sent emails and add some text to the body

**Comment by rainsworth** [comment]
The reply-to email should for now stay as fellows-management@software.ac.uk.
