### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#643]
We are cleaning up the lowFAT GitHub repo, and this issue compiles the issues opened in 2018 around GDPR to find out if they are still relevant (I have closed them to streamline things, and we can document what's needed in this new issue):
- Issue #458 
- Issue #459 
- Issue #460 
- Issue #461 
- Issue #462 
- Issue #463 

The current privacy policy is here: https://fellows.software.ac.uk/pages/privacy/.

@npch - Is the current policy sufficient, or does anything need to be updated/changed?

**Comment by npch** [comment]
@rainsworth I think that everything is covered for now.  #458, #461, #462, #463 are all adequately covered with the current policy and lowFAT functionality. The right to data portability (#460) isn't applicable in our case, I believe, but may help with #459.

The only issue we should be aware of is #459 - here, we should have a documented process for how we would handle a case where we need to retain a Fellows data but that it (for whatever reason) is not to be held on lowFAT. An example might be where an ex-Fellow has requested that the Community team is not allowed to view their information through lowFAT but it must be kept by us for tax reasons. I would suggest a manual process for now (e.g. is it enough for a copy of a backup to be stored separately, and the Fellow's record deleted from lowFAT) but potentially the ability to export/import a Fellows information from lowFAT might be put on a future lowFAT roadmap?
