### ISSUE TITLE
Update funding request page

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#681]
Find the changes we would like made to the [funding request page](https://fellows.software.ac.uk/request/) here: https://docs.google.com/document/d/1DzcBjRbh1cC-JUxnffgQJ2ltPIqJudRyTtTj7VhacWE/edit?usp=sharing (changes made in comments and suggestion mode)

**Comment by phillybroadbent** [comment]
Funding request form has been updated as shown in the word doc.
