### ISSUE TITLE
Resize images in docs

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#682]
The images in the Tutorial for Claimants and Tutorial for Staff sections of the lowFAT documentation are too large for the page - can they please be resized to fit on the page?

### Affected pages

Tutorial for Claimants
- https://softwaresaved.github.io/lowfat/claimant/claimant.html
- https://softwaresaved.github.io/lowfat/claimant/money.html
- https://softwaresaved.github.io/lowfat/claimant/status.html
- https://softwaresaved.github.io/lowfat/claimant/request.html
- https://softwaresaved.github.io/lowfat/claimant/expense.html
- https://softwaresaved.github.io/lowfat/claimant/blog.html

Tutorial for Staff
- https://softwaresaved.github.io/lowfat/staff/staff.html
- https://softwaresaved.github.io/lowfat/staff/request-review.html
- https://softwaresaved.github.io/lowfat/staff/expense-review.html
- https://softwaresaved.github.io/lowfat/staff/blog-review.html
- https://softwaresaved.github.io/lowfat/staff/constance.html
- https://softwaresaved.github.io/lowfat/staff/email.html

Note: eventually these images/screenshots will need to be replaced with updated ones, but that might need to wait until the next deployment.

**Comment by phillybroadbent** [comment]
I've resized the images and edited the navigation bar and header so that the major elements are using Bootstrap 5.  Users may need to perform a hard refresh in their browser to bypass the cache (as with the main site when bootstrap was updated). Please could you check if anything else needs editing @rainsworth ?

**Comment by phillybroadbent** [comment]
I've edited the Nav bar so that Claimant Workflow and Staff Workflow come first in their respective sections.
