### ISSUE TITLE
Update expense claim submission page

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#686]
Find the changes we would like made to the [expense claim submission page](https://fellows.software.ac.uk/expense/) here: https://docs.google.com/document/d/1Yt-L8Bg3jC90JMgvKudHZAHrSzfdwXn19u0EdAhT5Y4/edit?usp=sharing (changes made in comments and suggestion mode)

**Comment by phillybroadbent** [comment]
Changes made according to the google doc.
