### ISSUE TITLE
Funding request page fixes

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#696]
The following things on the on the [funding request page](https://fellows.software.ac.uk/request/) should be updated when possible:
- [ ] The default response for "Other costs (*)" should be "0.00" (it is currently set to "100.00" by default). 
- [ ] The default option for the "Will expenses related to this request need to be claimed directly via an invoice from your institution or supplier and the Institute?" tickbox should be FALSE (it is currently set to TRUE by default). 

<img width="722" alt="Screenshot 2023-01-30 at 13 31 57" src="https://user-images.githubusercontent.com/10600877/215491256-3cb746f1-bcb0-4ede-ae81-e08d7c83432e.png">

**Comment by phillybroadbent** [comment]
@rainsworth I can't replicate these issues and looking at the code the default for other costs is set to 0 and the tickbox is unchecked by default. When you enter a value it will remain even when you refresh the page, can you try submitting the form and then going back to the page to see whether the values have reset?

**Comment by rainsworth** [comment]
Yes, they have reset after submitting the form. 

That's strange that it saves the values from un-submitted forms even after leaving the page, I don't suppose there is any way to stop it from doing that?
