### ISSUE TITLE
There are two "Approved" options for reviewing funding requests

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#707]
When reviewing a funding request, there are currently two options for "Approved": 

<img width="1333" alt="Screenshot 2023-02-24 at 11 20 39" src="https://user-images.githubusercontent.com/10600877/221167251-580a8183-0dcd-471d-8232-2671a316dd5b.png">

Is there a difference between them or can we remove one?

**Comment by phillybroadbent** [comment]
@rainsworth I've had a look into it and the first 'Approved' represents the funding request being approved manually, whereas the second one represents the funding request being approved automatically by the machine.  Even though the labels are the same, the status code for each situation is different. Are both of these types of approval required? I could edit the label on the second 'Approved' to 'Approved by machine' as a simple way to distinguish between them or I can look into whether it would be possible to remove one from lowFAT entirely if you'd like to take that route?

**Comment by rainsworth** [comment]
Thank you @phillybroadbent! Editing the label on the second 'Approved' to 'Approved by machine' is a perfect solution - thanks!

**Comment by phillybroadbent** [comment]
Edited label for second 'Approved' to 'Approved by machine'.
