### ISSUE TITLE
Figure 4b sort options

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/lowfat#714]
Sort data so that the biggest group overall at the top and the smallest group overall at the bottom.

**Comment by robertn01** [comment]
![Image](https://user-images.githubusercontent.com/36110768/234955063-f354c00b-841e-4f91-b533-52ff3f226583.png)

**Comment by robertn01** [comment]
Removed filter on nr of jr RSE staff (AKA restored inclusion of all RSE groups). Also, excluded EPCC to optimise visual aesthetics e.g. y (value) scale [there's co-ord flip!].


![Image](https://user-images.githubusercontent.com/36110768/235280775-ae091202-a50c-4ba9-8306-31221d4ac749.png)
