### ISSUE TITLE
Allow funding requests to be made for past events

### ISSUE THREAD

**Issue by rainsworth** [softwaresaved/lowfat#722]
Currently, claimants are unable to submit funding requests for events in the past. While this is in line with our policies, in practice we have claimants who forget to submit a request in advance or there are cases where we are happy to approve the use of additional funds for past events as long as they are in line with the Fellowship and Institute. 

Start date and End date in the [funding request form](https://fellows.software.ac.uk/request/) should therefore not be limited to future dates if possible.

**Comment by phillybroadbent** [comment]
Removed date validation so that funding requests can be made for events in the past
