### ISSUE TITLE
Claim ~

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#725]
Claim #616, for £88.07.  When I am in the expense review page the budget approved is £0.00, but there is an approved budget on £89.40 when I look at Funding Request #616.  The status is "approved by machine", so I don't know if that is stopping the approved value showing on the claim page or if there is something else going on here.

**Comment by phillybroadbent** [comment]
Approved budget does not show up in expense review when the funding request is 'approved by machine' rather than 'approved'

**Comment by phillybroadbent** [comment]
Edited Budget approved field to include when budget is 'approved by machine'.
