### ISSUE TITLE
 "Red" Total doesn't match actual payments from inaugural fund

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#734]
Janetta queried the total of her expenses  - "Looking at lowFAT I have £254.29 but I thought I actually overspent (with permission of course 🙂 )".  I've had a look and she is overspent.  

There is a difference of £354.20 between what has been recorded as paid and what has been included in the total LF.  It may be that two payments haven't been picked up 562 and 564, totaling £354.23. 

I'd done a little reconciliation so I've attached it here.
[J Steyn - Lowfat Rec @18102023.xlsx](https://github.com/softwaresaved/lowfat/files/12999222/J.Steyn.-.Lowfat.Rec.%4018102023.xlsx)

**Comment by phillybroadbent** [comment]
I'm not sure how the functionality of lowFAT should change to fix this issue.  Maybe we can discuss this on slack if it remains an issue.
