### ISSUE TITLE
Deborah Leem - Approved Budget Request 618

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#735]
The approved budget that is showing in the approved list (Snip 1) isn't appearing in the Fellows page of Funding Requests/Expenses/ Blog posts (Snip 2).
This means that it is missing from the "Committed" line.  
It may be that the request was withdrawn, but if that is the case, should that be a status?

A claim hasn't been submitted for 618
![D Leem - Snip 1 - Fellows Page](https://github.com/softwaresaved/lowfat/assets/124907177/2fdff01a-408f-4060-939f-256a713996b0)
![D Leem - Snip 2 - Approved Budget Requests - 618](https://github.com/softwaresaved/lowfat/assets/124907177/cc8caf5b-9f92-40a0-8e11-8bc2fb2e5c12)

**Comment by phillybroadbent** [comment]
I'm going to close this issue as it relates to a particular case rather than the functionality of lowFAT.  We can discuss on slack if there is a particular behaviour or status that should be changed.
