### ISSUE TITLE
Sanjeet Kaur - Finance bar doesn't show paid and balance, committed - only £3,000 as committed. 

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#737]
![Sanjeet Kaur LF Query](https://github.com/softwaresaved/lowfat/assets/124907177/0a0beb0a-c01c-4c6e-8902-1f3883d6ffb3)

Saranjee has requestd £4,250 of expenses.  £1,066.44 has been approved for payment.  Rather than showing a £3,000 as committed in orange - see attached, it should be showing £1,066.44 in red (paid) and a balance of -£1,066.44 in green

![Sanjeet Kaur LF Query](https://github.com/softwaresaved/lowfat/assets/124907177/910a05cb-82ee-47c5-b7c1-8074e6f0eeb3)

**Comment by phillybroadbent** [comment]
In this case, the £1066.44 was for a compulsory event and therefore isn't subtracted from the total, so this functionality is as intended.
