### ISSUE TITLE
Ask in the Event Request how Fellows (or those they are supporting) will claim (e.g. expense, or invoice)

### ISSUE THREAD

**Issue by OscarSeip** [softwaresaved/lowfat#758]
Add a field to the funding request form which asks if the Fellow will hire someone else to do some work for them or if the SSI will be invoiced. If so, finance should be alerted so they can add them as a supplier.

**Comment by shoaibsufi** [comment]
At event request time check:

1. How they plan to claim
   1. Expense
   2. Invoice
   3. A combination (and if so a breakdown of how much for each)
2. If they are using their Fellowship to support others – how will the other(s) be claiming.
   1. Expense
   2. Invoice
   3. A combination

In the case whether it’s an invoice or a combination this should trigger an email to a designated email (e.g. could be SSI Finance or Fellow-Management) to take over the conversation around supplier registration and timescales.

**Comment by Kvglass** [comment]
We also need to ask about the type of "service" that is being paid for.  If we are paying for someone's time, (3 hrs @ £30 p/hr) this requires the payee to provide certain information re HMRC (a Unique tax ref no (UTR)), but if we are paying an honorarium, this would ususally be paid as a one-off payment, so no PO is required.

**Comment by gperu** [comment]
Will this funding request generate a payment:
- for you
- for a third party

If for you:
- expenses claim!

If payment to a third party:
- expenses claim (from somebody else)
- invoice

**Comment by gperu** [comment]
@Kvglass produce text to be added to funding request about:
- PO process
- supplier set-up

In easy lay terms.

**Comment by OscarSeip** [comment]
Duplicate issue #766 closed but contains screenshot of the tick box that needs changing.

**Comment by gperu** [comment]
Lay text from Finance:
https://docs.google.com/document/d/1sV7_43pqOGuypcZob-jAtRNQCj9GPqoLhfaPRWGQWpk/edit#heading=h.csiccmmund5i

**Comment by OscarSeip** [comment]
@phillybroadbent 
User story:_As a Finance Team member, I want to add a tick box to the funding request form that checks if the requested funds will be claimed via expense claim, invoice, or a combination of both, so that I can easily determine the payment method and trigger appropriate processes such as Purchase Orders and Employment Status Checks if necessary._

Suggested implementation:   
- Add description, as added in commit fd447eb.
- Replace current tickbox with two required questions. 

1. Who will receive the payment?
A. Me (the Fellow)
B. Third party
C. Combination of both

2. How will you or they be claiming?
A. Expense claim
B. Invoice
C. Combination of both

- If answers 1B, 1C, 2B, or 2C are selected this should trigger an email to finance@software.ac.uk: 

On **[date]**, **[user]** submitted a funding request which might require a Purchase Order or Employment Status Check. Please investigate and if needed contact **[user]** in relation to this request.
