### ISSUE TITLE
'Remove' buttons behave differently

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#763]
'Remove' buttons behave differently in the funding request, expense and blogopost review page.

Larger issue is: should we removing things at all from the system.

**Comment by OscarSeip** [comment]
Update: No funding request should be completed deleted from the system.

**Comment by phillybroadbent** [comment]
Currently, clicking the 'Remove' button in the detail view or clicking the 'x' in the dashboard table will delete the funding request/expense claim/blog post from the system altogether.  Setting the status to 'Remove' in the review form will remove the item from the dashboard but it will still be available in the admin area of lowfat.  I suggest that the 'Remove' button in detail view and 'x' in table could be deleted, leaving only the option to set the status to 'Remove'.

**Comment by gperu** [comment]
Implementation:
- remove the 'remove' button
- keep the 'remove' status
- 'remove' status removes a submission from lowFAT dashboard
- submision is kept in lowFAT admin

See screenshots attached,

![Image](https://github.com/user-attachments/assets/2dd86b74-f450-4d40-8032-8d6ce9665ebd)
![Image](https://github.com/user-attachments/assets/032bec09-c05e-4538-8c41-e5fce3bd3447)
![Image](https://github.com/user-attachments/assets/51b47b91-de16-4734-9d79-26926b7f8d42)

**Comment by phillybroadbent** [comment]
I've implemented the solution suggested above
