### ISSUE TITLE
Link to UoE Expenses Claim form leads to wrong form

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#765]
In the Submit expense claim page [https://fellows.software.ac.uk/expense/ ](url)

No 2 states:
"You MUST fill out the [University of Edinburgh Payment of Non-Staff Expenses form](https://www.ed.ac.uk/sites/default/files/atoms/files/non_staff_expenses_claim_form_v3.docx)."

While this link leads to the UoE form, it doesn't contain the additional table for a breakdown of expenses.
The form we use at SSI  is attached
[BLANK  Non_staff_expenses_claim_form_-_with_list_2023.docx](https://github.com/softwaresaved/lowfat/files/14762342/BLANK.Non_staff_expenses_claim_form_-_with_list_2023.docx)

Can this link be updated please?

**Comment by phillybroadbent** [comment]
I've change the link to https://www.software.ac.uk/guide/guidelines-reimbursement-expenses-supported-software-sustainability-institute as Oscar suggested.  Therefore, if the form changes again it will only need to be updated on the SSI website and not on lowFAT as well.
