### ISSUE TITLE
Third Party Invoices

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#766]
When adding a request there is a box at the bottom of the Costs section 

"Will expenses related to this request need to be claimed directly via an invoice from your institution or supplier and the Institute?" 

![image](https://github.com/softwaresaved/lowfat/assets/124907177/ca2558cb-3324-4a62-9235-e3ce2f56d984)

I think this needs to be bigger and have more explanation as this seems to be missed by many fellows who are paying someone else, but don't realize they need to check this box.

**Comment by gperu** [comment]
Duplicate. See #758
