### ISSUE TITLE
Fellow with 2 Accounts

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#773]
Hi 
We seem to have two accounts for the same fellow.
Funding request & Claim for ID645 shows on a different page from Funding request & Claim for IDs 732 &733.
Both are for the same fellow.

![image](https://github.com/softwaresaved/lowfat/assets/124907177/ed1e5dc3-fb75-472b-beb1-0aa5e0c88605)

![image](https://github.com/softwaresaved/lowfat/assets/124907177/63e0de26-d4af-47e1-9210-360893f49a13)

**Comment by gperu** [comment]
See #778
