### ISSUE TITLE
UoE Supplier Number Box

### ISSUE THREAD

**Issue by Kvglass** [softwaresaved/lowfat#775]
Can a box for the UoE supplier no be added to the profile page of each fellow please?

The supplier no is created after the first claim has been received by UoE central finance.

At the moment we are inserting the UoE supplier no into every claim form that is subsequently submitted and I think it might make sense (and reduce some of our work) if Fellows could see this no and insert it into the claim form before it is uploaded.

The supplier no is currently 5 digits (current no is around 55560), but we could future-proof the box by making it big enough for 6 digits.

**Comment by phillybroadbent** [comment]
@gperu @Kvglass 

After talking with Giacomo we have the following idea of how to implement this - The supplier number would be added as an attribute to the fellow model and would be displayed in the fellow's profile alongside their other information.  The supplier number could be added through the admin interface of lowFAT.

**Comment by Kvglass** [comment]
Yes, this sounds pefrect, thank you!

**Comment by phillybroadbent** [comment]
Added supplier number field to claimant model, made available to edit in admin interface and to view in fellow profile (if authenticated user is the fellow or staff).

**Comment by Kvglass** [comment]
Hi Philly, I don't easily see this box, could we have a a quick 5 mins catchup so I can make sure I'm looking at the right page?

**Comment by phillybroadbent** [comment]
Hi Kathleen, this change hasn't been deployed to the actual lowFAT yet, it's only on the development version.  When we deploy the new changes I'll let you know :)

**Comment by Kvglass** [comment]
hahah - oops!, thank you.
